title: Healthier SG Care Protocols Demo site
url: https://www.healthiersg.gov.sg
favicon: /images/medica_health_healthcare_sign_icon_143444.ico
colors:
  primary-color: "#4a90e2"
  secondary-color: "#4a90e2"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#4a90e2"
    - title: media-color-three
      color: "#4a90e2"
    - title: media-color-four
      color: "#4a90e2"
    - title: media-color-five
      color: "#4a90e2"
description: Healthier SG Care Protocols Demo site
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://moht-isomersandbox-staging.netlify.app/
prod: https://moht-isomersandbox-prod.netlify.app/
google_analytics: UA-149609309-2
shareicon: /images/isomer-logo.svg
is_government: false
facebook-pixel: ""
linkedin-insights: ""
resources_name: healthier-sg
google_analytics_ga4: G-2LY9PQL8S1
